### ISSUE TITLE
Sample of tweet_keys_file.txt

### ISSUE THREAD

**Issue by xingsumq** [SaschaStenger/FakeNewsNet_modified#20]
Hi @SaschaStenger , 

Thank you so much for providing a modified vision. When I tried to provide tweet keys, as I don't know the read format of keys in 'tweet_keys_file.txt', the code always got keys failed. Could you please provide a empty file of 'tweet_keys_file.txt', so that we can know the input format of keys. Much appreciated!

**Comment by SaschaStenger** [comment]
The format would be:
app_key,app_secret,oauth_token,oauth_token_secret
as the headers in your csv file
Added an example file under [code/resources/tweet_keys_file.txt](https://github.com/SaschaStenger/FakeNewsNet_modified/blob/master/code/resources/tweet_keys_file.txt)

**Comment by forAlgorithm** [comment]
I'm having some trouble getting development access, can you please provide me with a Google Cloud Drive for easy download? Thank you!

**Comment by jannat5134** [comment]
did you find the database?
