### ISSUE TITLE
Can you give a Baidu web disk link, including the complete data set?

### ISSUE THREAD

**Issue by TpBlair** [SaschaStenger/FakeNewsNet_modified#43]

**Comment by jannat5134** [comment]
did you find the complete data set?

**Comment by SaschaStenger** [comment]
At the time, that the dateset was created, the twitter terms of service did not allow for the sharing of a complete dataset. 
I have not looked, if their ToS have changed since then, but it was forbidden to share a complete dataset and you had to download it yourself with your own api access token.
